import { withCors, preflight } from '@/lib/utils/cors';

// Lista completa de zonas horarias IANA (IANA Time Zone Database)
// Estas son las zonas horarias estándar reconocidas internacionalmente
const TIMEZONES = [
  // UTC
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  
  // América del Norte
  { value: 'America/New_York', label: 'America/New_York (Eastern Time)' },
  { value: 'America/Chicago', label: 'America/Chicago (Central Time)' },
  { value: 'America/Denver', label: 'America/Denver (Mountain Time)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (Pacific Time)' },
  { value: 'America/Phoenix', label: 'America/Phoenix (Mountain Standard Time)' },
  { value: 'America/Anchorage', label: 'America/Anchorage (Alaska Time)' },
  { value: 'America/Juneau', label: 'America/Juneau (Alaska Time)' },
  { value: 'America/Sitka', label: 'America/Sitka (Alaska Time)' },
  { value: 'America/Metlakatla', label: 'America/Metlakatla (Alaska Time)' },
  { value: 'America/Yakutat', label: 'America/Yakutat (Alaska Time)' },
  { value: 'America/Nome', label: 'America/Nome (Alaska Time)' },
  { value: 'America/Adak', label: 'America/Adak (Hawaii-Aleutian Time)' },
  { value: 'America/Honolulu', label: 'America/Honolulu (Hawaii Time)' },
  { value: 'America/Toronto', label: 'America/Toronto (Eastern Time)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (Pacific Time)' },
  { value: 'America/Winnipeg', label: 'America/Winnipeg (Central Time)' },
  { value: 'America/Edmonton', label: 'America/Edmonton (Mountain Time)' },
  { value: 'America/Halifax', label: 'America/Halifax (Atlantic Time)' },
  { value: 'America/St_Johns', label: 'America/St_Johns (Newfoundland Time)' },
  { value: 'America/Whitehorse', label: 'America/Whitehorse (Pacific Time)' },
  { value: 'America/Yellowknife', label: 'America/Yellowknife (Mountain Time)' },
  { value: 'America/Inuvik', label: 'America/Inuvik (Mountain Time)' },
  { value: 'America/Iqaluit', label: 'America/Iqaluit (Eastern Time)' },
  { value: 'America/Glace_Bay', label: 'America/Glace_Bay (Atlantic Time)' },
  { value: 'America/Moncton', label: 'America/Moncton (Atlantic Time)' },
  { value: 'America/Goose_Bay', label: 'America/Goose_Bay (Atlantic Time)' },
  { value: 'America/Blanc-Sablon', label: 'America/Blanc-Sablon (Atlantic Standard Time)' },
  { value: 'America/Montreal', label: 'America/Montreal (Eastern Time)' },
  { value: 'America/Thunder_Bay', label: 'America/Thunder_Bay (Eastern Time)' },
  { value: 'America/Nipigon', label: 'America/Nipigon (Eastern Time)' },
  { value: 'America/Rainy_River', label: 'America/Rainy_River (Central Time)' },
  { value: 'America/Atikokan', label: 'America/Atikokan (Eastern Standard Time)' },
  { value: 'America/Cambridge_Bay', label: 'America/Cambridge_Bay (Mountain Time)' },
  { value: 'America/Dawson', label: 'America/Dawson (Pacific Time)' },
  { value: 'America/Dawson_Creek', label: 'America/Dawson_Creek (Mountain Standard Time)' },
  { value: 'America/Fort_Nelson', label: 'America/Fort_Nelson (Mountain Standard Time)' },
  { value: 'America/Regina', label: 'America/Regina (Central Standard Time)' },
  { value: 'America/Swift_Current', label: 'America/Swift_Current (Central Standard Time)' },
  
  // México
  { value: 'America/Mexico_City', label: 'America/Mexico_City (Central Time)' },
  { value: 'America/Monterrey', label: 'America/Monterrey (Central Time)' },
  { value: 'America/Tijuana', label: 'America/Tijuana (Pacific Time)' },
  { value: 'America/Cancun', label: 'America/Cancun (Eastern Time)' },
  { value: 'America/Merida', label: 'America/Merida (Central Time)' },
  { value: 'America/Mazatlan', label: 'America/Mazatlan (Mountain Time)' },
  { value: 'America/Chihuahua', label: 'America/Chihuahua (Mountain Time)' },
  { value: 'America/Hermosillo', label: 'America/Hermosillo (Mountain Standard Time)' },
  { value: 'America/Bahia_Banderas', label: 'America/Bahia_Banderas (Central Time)' },
  { value: 'America/Matamoros', label: 'America/Matamoros (Central Time)' },
  { value: 'America/Ojinaga', label: 'America/Ojinaga (Mountain Time)' },
  
  // América Central
  { value: 'America/Guatemala', label: 'America/Guatemala (Central Time)' },
  { value: 'America/Belize', label: 'America/Belize (Central Time)' },
  { value: 'America/El_Salvador', label: 'America/El_Salvador (Central Time)' },
  { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa (Central Time)' },
  { value: 'America/Managua', label: 'America/Managua (Central Time)' },
  { value: 'America/Costa_Rica', label: 'America/Costa_Rica (Central Time)' },
  { value: 'America/Panama', label: 'America/Panama (Eastern Standard Time)' },
  
  // Caribe
  { value: 'America/Havana', label: 'America/Havana (Cuba Time)' },
  { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo (Atlantic Time)' },
  { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico (Atlantic Standard Time)' },
  { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince (Eastern Time)' },
  { value: 'America/Jamaica', label: 'America/Jamaica (Eastern Standard Time)' },
  { value: 'America/Nassau', label: 'America/Nassau (Eastern Time)' },
  { value: 'America/Barbados', label: 'America/Barbados (Atlantic Standard Time)' },
  { value: 'America/Aruba', label: 'America/Aruba (Atlantic Standard Time)' },
  { value: 'America/Curacao', label: 'America/Curacao (Atlantic Standard Time)' },
  { value: 'America/Marigot', label: 'America/Marigot (Atlantic Standard Time)' },
  { value: 'America/Martinique', label: 'America/Martinique (Atlantic Standard Time)' },
  { value: 'America/St_Barthelemy', label: 'America/St_Barthelemy (Atlantic Standard Time)' },
  { value: 'America/St_Kitts', label: 'America/St_Kitts (Atlantic Standard Time)' },
  { value: 'America/St_Lucia', label: 'America/St_Lucia (Atlantic Standard Time)' },
  { value: 'America/St_Thomas', label: 'America/St_Thomas (Atlantic Standard Time)' },
  { value: 'America/St_Vincent', label: 'America/St_Vincent (Atlantic Standard Time)' },
  { value: 'America/Tortola', label: 'America/Tortola (Atlantic Standard Time)' },
  
  // América del Sur
  { value: 'America/Bogota', label: 'America/Bogota (Colombia Time)' },
  { value: 'America/Lima', label: 'America/Lima (Peru Time)' },
  { value: 'America/Quito', label: 'America/Quito (Ecuador Time)' },
  { value: 'America/La_Paz', label: 'America/La_Paz (Bolivia Time)' },
  { value: 'America/Santiago', label: 'America/Santiago (Chile Time)' },
  { value: 'America/Argentina/Buenos_Aires', label: 'America/Argentina/Buenos_Aires (Argentina Time)' },
  { value: 'America/Argentina/Cordoba', label: 'America/Argentina/Cordoba (Argentina Time)' },
  { value: 'America/Argentina/Salta', label: 'America/Argentina/Salta (Argentina Time)' },
  { value: 'America/Argentina/Jujuy', label: 'America/Argentina/Jujuy (Argentina Time)' },
  { value: 'America/Argentina/Tucuman', label: 'America/Argentina/Tucuman (Argentina Time)' },
  { value: 'America/Argentina/Catamarca', label: 'America/Argentina/Catamarca (Argentina Time)' },
  { value: 'America/Argentina/La_Rioja', label: 'America/Argentina/La_Rioja (Argentina Time)' },
  { value: 'America/Argentina/San_Juan', label: 'America/Argentina/San_Juan (Argentina Time)' },
  { value: 'America/Argentina/Mendoza', label: 'America/Argentina/Mendoza (Argentina Time)' },
  { value: 'America/Argentina/San_Luis', label: 'America/Argentina/San_Luis (Argentina Time)' },
  { value: 'America/Argentina/Rio_Gallegos', label: 'America/Argentina/Rio_Gallegos (Argentina Time)' },
  { value: 'America/Argentina/Ushuaia', label: 'America/Argentina/Ushuaia (Argentina Time)' },
  { value: 'America/Montevideo', label: 'America/Montevideo (Uruguay Time)' },
  { value: 'America/Asuncion', label: 'America/Asuncion (Paraguay Time)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (Brasilia Time)' },
  { value: 'America/Caracas', label: 'America/Caracas (Venezuela Time)' },
  { value: 'America/Guyana', label: 'America/Guyana (Guyana Time)' },
  { value: 'America/Paramaribo', label: 'America/Paramaribo (Suriname Time)' },
  { value: 'America/Cayenne', label: 'America/Cayenne (French Guiana Time)' },
  { value: 'America/Manaus', label: 'America/Manaus (Amazon Time)' },
  { value: 'America/Belem', label: 'America/Belem (Brasilia Time)' },
  { value: 'America/Fortaleza', label: 'America/Fortaleza (Brasilia Time)' },
  { value: 'America/Recife', label: 'America/Recife (Brasilia Time)' },
  { value: 'America/Araguaina', label: 'America/Araguaina (Brasilia Time)' },
  { value: 'America/Maceio', label: 'America/Maceio (Brasilia Time)' },
  { value: 'America/Bahia', label: 'America/Bahia (Brasilia Time)' },
  { value: 'America/Noronha', label: 'America/Noronha (Fernando de Noronha Time)' },
  { value: 'America/Porto_Velho', label: 'America/Porto_Velho (Amazon Time)' },
  { value: 'America/Rio_Branco', label: 'America/Rio_Branco (Acre Time)' },
  { value: 'America/Campo_Grande', label: 'America/Campo_Grande (Amazon Time)' },
  { value: 'America/Cuiaba', label: 'America/Cuiaba (Amazon Time)' },
  
  // Europa
  { value: 'Europe/London', label: 'Europe/London (GMT/BST)' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin (GMT/IST)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET/CEST)' },
  { value: 'Europe/Brussels', label: 'Europe/Brussels (CET/CEST)' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (CET/CEST)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (CET/CEST)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (CET/CEST)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (CET/CEST)' },
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon (WET/WEST)' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna (CET/CEST)' },
  { value: 'Europe/Zurich', label: 'Europe/Zurich (CET/CEST)' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm (CET/CEST)' },
  { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen (CET/CEST)' },
  { value: 'Europe/Oslo', label: 'Europe/Oslo (CET/CEST)' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki (EET/EEST)' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw (CET/CEST)' },
  { value: 'Europe/Prague', label: 'Europe/Prague (CET/CEST)' },
  { value: 'Europe/Budapest', label: 'Europe/Budapest (CET/CEST)' },
  { value: 'Europe/Bucharest', label: 'Europe/Bucharest (EET/EEST)' },
  { value: 'Europe/Sofia', label: 'Europe/Sofia (EET/EEST)' },
  { value: 'Europe/Athens', label: 'Europe/Athens (EET/EEST)' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul (TRT)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (MSK)' },
  { value: 'Europe/Kiev', label: 'Europe/Kiev (EET/EEST)' },
  { value: 'Europe/Minsk', label: 'Europe/Minsk (MSK)' },
  { value: 'Europe/Riga', label: 'Europe/Riga (EET/EEST)' },
  { value: 'Europe/Tallinn', label: 'Europe/Tallinn (EET/EEST)' },
  { value: 'Europe/Vilnius', label: 'Europe/Vilnius (EET/EEST)' },
  
  // Asia
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (HKT)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (KST)' },
  { value: 'Asia/Taipei', label: 'Asia/Taipei (CST)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (ICT)' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta (WIB)' },
  { value: 'Asia/Manila', label: 'Asia/Manila (PHT)' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur (MYT)' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh (ICT)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST)' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka (BDT)' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi (PKT)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (GST)' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh (AST)' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran (IRST)' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem (IST/IDT)' },
  { value: 'Asia/Baghdad', label: 'Asia/Baghdad (AST)' },
  { value: 'Asia/Baku', label: 'Asia/Baku (AZT)' },
  { value: 'Asia/Yerevan', label: 'Asia/Yerevan (AMT)' },
  { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi (GET)' },
  { value: 'Asia/Almaty', label: 'Asia/Almaty (ALMT)' },
  { value: 'Asia/Bishkek', label: 'Asia/Bishkek (KGT)' },
  { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe (TJT)' },
  { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat (TMT)' },
  { value: 'Asia/Tashkent', label: 'Asia/Tashkent (UZT)' },
  { value: 'Asia/Samarkand', label: 'Asia/Samarkand (UZT)' },
  { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg (YEKT)' },
  { value: 'Asia/Omsk', label: 'Asia/Omsk (OMST)' },
  { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk (KRAT)' },
  { value: 'Asia/Novosibirsk', label: 'Asia/Novosibirsk (NOVT)' },
  { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk (IRKT)' },
  { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk (YAKT)' },
  { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok (VLAT)' },
  { value: 'Asia/Magadan', label: 'Asia/Magadan (MAGT)' },
  { value: 'Asia/Sakhalin', label: 'Asia/Sakhalin (SAKT)' },
  { value: 'Asia/Kamchatka', label: 'Asia/Kamchatka (PETT)' },
  { value: 'Asia/Anadyr', label: 'Asia/Anadyr (ANAT)' },
  
  // Australia y Pacífico
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEDT/AEST)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (AEDT/AEST)' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane (AEST)' },
  { value: 'Australia/Perth', label: 'Australia/Perth (AWST)' },
  { value: 'Australia/Adelaide', label: 'Australia/Adelaide (ACDT/ACST)' },
  { value: 'Australia/Darwin', label: 'Australia/Darwin (ACST)' },
  { value: 'Australia/Hobart', label: 'Australia/Hobart (AEDT/AEST)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZDT/NZST)' },
  { value: 'Pacific/Fiji', label: 'Pacific/Fiji (FJT)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (HST)' },
  { value: 'Pacific/Guam', label: 'Pacific/Guam (ChST)' },
  { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby (PGT)' },
  { value: 'Pacific/Noumea', label: 'Pacific/Noumea (NCT)' },
  { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti (TAHT)' },
  { value: 'Pacific/Apia', label: 'Pacific/Apia (WST)' },
  { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu (TOT)' },
  
  // África
  { value: 'Africa/Cairo', label: 'Africa/Cairo (EET)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (WAT)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (EAT)' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca (WET)' },
  { value: 'Africa/Algiers', label: 'Africa/Algiers (CET)' },
  { value: 'Africa/Tunis', label: 'Africa/Tunis (CET)' },
  { value: 'Africa/Tripoli', label: 'Africa/Tripoli (EET)' },
  { value: 'Africa/Khartoum', label: 'Africa/Khartoum (CAT)' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa (EAT)' },
  { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam (EAT)' },
  { value: 'Africa/Kampala', label: 'Africa/Kampala (EAT)' },
  { value: 'Africa/Maputo', label: 'Africa/Maputo (CAT)' },
  { value: 'Africa/Harare', label: 'Africa/Harare (CAT)' },
  { value: 'Africa/Lusaka', label: 'Africa/Lusaka (CAT)' },
  { value: 'Africa/Accra', label: 'Africa/Accra (GMT)' },
  { value: 'Africa/Abidjan', label: 'Africa/Abidjan (GMT)' },
  { value: 'Africa/Dakar', label: 'Africa/Dakar (GMT)' },
  { value: 'Africa/Luanda', label: 'Africa/Luanda (WAT)' },
];

export async function OPTIONS(request: Request) {
  const origin = request.headers.get('origin');
  return preflight(origin);
}

export async function GET(request: Request) {
  try {
    const origin = request.headers.get('origin');
    return withCors(origin, Response.json({ timezones: TIMEZONES }));
  } catch (error) {
    return Response.json({ error: 'Failed to fetch timezones' }, { status: 500 });
  }
}

